### PR TITLE
Rename token object

### PR DESCRIPTION
**Pull request by ejaypcanaria**

### CODE REVIEW

**Comment by ejaypcanaria** [comment]
Curious about who's using this library other than Iguana?

**Comment by bradleypriest** [comment]
All of our internal tools and probably a couple of third parties as well

**Comment by ejaypcanaria** [comment]
I see. Is this safe to merge knowing that `token` is currently exposed as public method?

**Comment by bradleypriest** [comment]
Just add a note to the README about the change, and maybe rename to `original_token` or `raw_token` or something?

**Comment by ejaypcanaria** [comment]
Brad, all done. Let me know if this looks good.

**Comment by bradleypriest** [comment]
:smile:

**Pull request merged**
